sudo: required

language: python
python:
- "2.7"

services:
    - docker

before_install:
    - docker build -t pfcm/tml .

script:
    - docker run pfcm/tml

# if a successful push to master, should rebuild the docker containers
# and push to gcr.io. However, that's all future stuff atm.
