language: python
python:
- "2.7"

install:
    - "pip install -r requirements.txt"
    - "pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl"
script: "nosetests"

# if a successful push to master, should rebuild the docker containers
# and push to gcr.io. However, that's all future stuff atm.
